### ISSUE TITLE
Default config

### ISSUE THREAD

**Issue by kazimir-malevich** [tag1consulting/goose#439]
Do you think print() and StatusCodes should be made default? We'd definitely want to see percentiles at the end of the test run and HTTP status codes are useful as well. I'm thinking more towards new users.

**Comment by jeremyandrews** [comment]
We already committed a a PR to print() by default which will be in `0.16` when released, see:
As of https://github.com/tag1consulting/goose/pull/379

I'm not opposed to changing `--status-codes` to `--no-status-codes` so we collect and display the Status Code table by default, PR welcome (documentation will also need to be updated). The current default is because there is a small amount of performance and memory overhead to enabling this option, but I generally always enable it when I'm running load tests anyway so it's a logical default.

**Comment by kazimir-malevich** [comment]
Where's the Goose binary?
```
$:~/projects/goose$ cargo build --release
Finished release [optimized] target(s) in 0.12s
$:~/projects/goose$ cd target/release/
$~/projects/goose/target/release$ ls
build  deps  examples  incremental  libgoose.d  libgoose.rlib
```

**Comment by jeremyandrews** [comment]
Goose itself is a library, so there is no binary. You can build an example to create a binary, or create a load test as documented in the book to create a binary with it.
